language: python
python: 
  - "3.10"
before_install:
  - python -m pip install --upgrade pip
install: 
  - python -v
  - pip install -r requirements.txt
  - source $HOME/scraper/pyscraper/venv/bin/activate
  - cd $HOME/scraper/pyscraper/webscraper
