version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  base-directory: 'aws'
  files:
    - '**/*'
